trigger:
- main

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'

steps:
- task: Npm@1
  inputs:
    command: 'install'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Angular-Azure-Microservices.csproj'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'bin\Debug\net6.0\**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
